export const FETCH_WEB3_CONNECTION_REQUESTED = "App/FETCH_WEB3_CONNECTION_REQUESTED"
export const FETCH_WEB3_CONNECTION_SUCCESS = "App/FETCH_WEB3_CONNECTION_SUCCESS"
export const FETCH_WEB3_CONNECTION_FAILED = "App/FETCH_WEB3_CONNECTION_FAILED"

// 以下に自分が使うアクションを定義
