export const SET_FRIEND_ADDRESS = "App/SET_FRIEND_ADDRESS"

export const FETCH_HISTORY_REQUESTED = "App/FETCH_HISTORY_REQUESTED"
export const FETCH_HISTORY_SUCCESS = "App/FETCH_HISTORY_SUCCESS"
export const FETCH_HISTORY_FAILED = "App/FETCH_HISTORY_FAILED"

export const SEND_MESSAGE_REQUESTED = "App/SEND_MESSAGE_REQUESTED"
export const SEND_MESSAGE_SUCCESS = "App/SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAILED = "App/SEND_MESSAGE_FAILED"

export const FETCH_WEB3_CONNECTION_REQUESTED = "App/FETCH_WEB3_CONNECTION_REQUESTED"
export const FETCH_WEB3_CONNECTION_SUCCESS = "App/FETCH_WEB3_CONNECTION_SUCCESS"
export const FETCH_WEB3_CONNECTION_FAILED = "App/FETCH_WEB3_CONNECTION_FAILED"
